wallpaper { 
    monitor = DP-2
    path = /home/tkim/wallpapers/hollow-knight.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/tkim/wallpapers/hollow-knight-portrait.jpg
    fit_mode = cover
}

